### PR TITLE
More options to access changed values

### PR DESCRIPTION
**Pull request by gamma**
The PR adds the options `outputTimeInSeconds` and `outputSecurityLevel` to have access to their values in callback methods.

### CODE REVIEW

**Comment by smallhadroncollider** [comment]
Sorry for such a slow response. I've been busy with work/child/working on new version of HSIMP code.

I'm hoping to update this to use the newer version of the code.

The newer version uses BigInt to support arbitrarily large numbers. As such I'm not sure if returning the time in seconds would necessarily be useful: it would need to be returned as a string (as the value would often be outside of the limits of `Number`). Would that still be useful?

**Comment by gamma** [comment]
That is quite alright.

I'm currently using the handler to decide whether it is ok accept the password or not. That is: comparing the timeInSeconds against the configured "ok" value.

How will the "ok" and "good" values be configured later? If there is another way to have that kind of response I'm OK with not having the timeInSeconds function.

**Comment by smallhadroncollider** [comment]
Actually having that exact discussion over here: https://github.com/howsecureismypassword/modules-purescript/issues/8

**Comment by gamma** [comment]
Sorry to bother you on this, but you referenced this PR in your comment. Is there another issue open about the same topic that I am missing?

**Comment by smallhadroncollider** [comment]
🤦‍♂️Have updated the link

**Pull request closed without merging**
